### PR TITLE
adding environment to the naming instances

### PR DESCRIPTION
**Pull request by Lucasosf**
To see more easily what is what in the aws console, I think is necessary add the environment on the name beyond the tags.
The environment in the tags is useful to the cost explorer e on the name is useful to filter more easily.

Everybody agree with it?

### CODE REVIEW

**Comment by rubendebest** [comment]
Just think it is important to add that `production` is the default `env`, and that other envs are explicitly named. 
For the rest, :+1:

**Comment by Lucasosf** [comment]
I agree with you. =)

**Comment by jao** [comment]
I disagree.
I've said that before, machines are not exactly applications. Specially when it comes to development machines. Where you have several applications running in a single machine.

**Comment by Lucasosf** [comment]
Then what you think that we can do about it?
Maybe can we name like 'dev.01.beable' and 'dev.01.bi' to group apps in the development enviroment, but keeping updated the documentations about where are the apps?

I think in production environment is kind of unusual, right? oO

**Comment by jao** [comment]
to illustrate the issue:
dev.01.beagle runs jenkins
is jenkins limited only to beagle? no.
Unless we move jenkins to a different machine.

It would probably make more sense to name the machine web.01.devtools or something like that, if we keep it as is.

**Comment by jao** [comment]
To be productive, we should probably focus on the issue at hand, we don't know what runs where (machine) and where (zone) machines are hosted. Right?

What is really important to us, at this moment?
Knowing where they are (zone)? or knowing what (machine) runs what (application)?

Maybe a simple graphic could solve this, without trying to complicate naming conventions that don't really fit our daily needs.

**Comment by Lucasosf** [comment]
That's ok. :stuck_out_tongue:

**Comment by jao** [comment]
sigh :p

**Pull request closed without merging**
